# Generated by Django 3.2.5 on 2021-08-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_data', '0003_auto_20210804_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbsdata',
            fields=[
                ('帖子标题', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='帖子标题')),
                ('帖子内容', models.TextField(max_length=9999999, null=True, verbose_name='帖子内容')),
                ('发帖时间', models.DateTimeField(null=True, verbose_name='发贴时间')),
                ('论坛分区', models.CharField(max_length=88, null=True, verbose_name='论坛分区')),
                ('点赞数', models.IntegerField(default=0, verbose_name='点赞数')),
                ('收藏数', models.IntegerField(default=0, verbose_name='收藏数')),
                ('浏览次数', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('是否审核通过', models.BooleanField(default=0, verbose_name='是否审核通过')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': 'BBS数据',
            },
        ),
        migrations.CreateModel(
            name='Comment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('楼数', models.IntegerField(verbose_name='楼数')),
                ('评论内容', models.TextField(max_length=9999999, null=True, verbose_name='评论内容')),
                ('评论时间', models.DateTimeField(null=True, verbose_name='评论时间')),
                ('帖子标题', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BBS.bbsdata')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '帖子评论',
                'unique_together': {('帖子标题', '楼数')},
            },
        ),
        migrations.CreateModel(
            name='Report_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('举报时间', models.DateTimeField(null=True, verbose_name='举报时间')),
                ('举报理由', models.TextField(max_length=9999999, null=True, verbose_name='举报理由')),
                ('是否审核通过', models.BooleanField(default=0, verbose_name='是否审核通过')),
                ('举报用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
                ('帖子标题', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BBS.bbsdata')),
            ],
            options={
                'db_table': '用户举报',
                'unique_together': {('帖子标题', '举报用户')},
            },
        ),
        migrations.CreateModel(
            name='Reply_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论号', models.IntegerField(null=True, verbose_name='评论号')),
                ('评论内容', models.TextField(max_length=9999999, null=True, verbose_name='评论内容')),
                ('评论时间', models.DateTimeField(null=True, verbose_name='评论时间')),
                ('回复的评论', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BBS.comment_data')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '评论回复',
                'unique_together': {('回复的评论', '评论号')},
            },
        ),
    ]
