# Generated by Django 3.2.5 on 2021-08-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setactivity',
            name='是否通过审核',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='是否通过审核'),
        ),
    ]
