# Generated by Django 3.2.5 on 2021-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='姓名_组织名',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='家庭年收入',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='家庭年收入'),
        ),
        migrations.AlterField(
            model_name='user',
            name='密码',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='居住城市',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='居住城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='手机号',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='是否实名认证',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='是否实名认证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='是否通过家庭收入认证',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='是否通过家庭收入认证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='是否通过社会组织认证',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='是否通过社会组织认证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='用户类型',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='组织描述',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='组织描述'),
        ),
        migrations.AlterField(
            model_name='user',
            name='组织类型',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='组织类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='身份证号',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='邮箱',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮箱'),
        ),
    ]
