# Generated by Django 3.2.5 on 2021-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20210802_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='sick_children',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='sick_children',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='sick_children',
            name='认证图片',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='identifypicture', verbose_name='认证图片', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='user',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='user',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='user',
            name='用户头像',
            field=models.ImageField(height_field='url_height', null=True, upload_to='headpicture', verbose_name='用户头像', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='user',
            name='认证图片',
            field=models.ImageField(height_field='url_height', null=True, upload_to='identifypicture', verbose_name='认证图片', width_field='url_width'),
        ),
    ]
