# Generated by Django 3.2.5 on 2021-08-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_data', '0003_auto_20210804_1634'),
        ('Activity', '0002_setactivity_是否通过审核'),
        ('BBS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_thumb_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('点赞时间', models.DateTimeField(null=True, verbose_name='点赞时间')),
                ('帖子', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BBS.bbsdata')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '用户点赞帖子',
                'unique_together': {('用户', '帖子')},
            },
        ),
        migrations.CreateModel(
            name='User_thumb_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('点赞时间', models.DateTimeField(null=True, verbose_name='点赞时间')),
                ('活动', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activity.activity')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '用户点赞活动',
                'unique_together': {('用户', '活动')},
            },
        ),
        migrations.CreateModel(
            name='User_collect_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('收藏时间', models.DateTimeField(null=True, verbose_name='收藏时间')),
                ('帖子', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BBS.bbsdata')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '用户收藏帖子',
                'unique_together': {('用户', '帖子')},
            },
        ),
        migrations.CreateModel(
            name='User_collect_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('收藏时间', models.DateTimeField(null=True, verbose_name='收藏时间')),
                ('活动', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activity.activity')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '用户收藏活动',
                'unique_together': {('用户', '活动')},
            },
        ),
        migrations.CreateModel(
            name='Activity_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('发起的活动', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activity.setactivity')),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_data.user')),
            ],
            options={
                'db_table': '活动报名',
                'unique_together': {('用户', '发起的活动')},
            },
        ),
    ]
